# Generated by Django 4.1 on 2022-09-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_comment_commentator_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Видимость статьи'),
        ),
    ]
