# Generated by Django 4.1 on 2022-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_profile_bio_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
    ]
